whereby/sdk

.github/workflows/test.yml
**Summary:**
@havardholvik
@kevinwhereby
@nandito
@thyal
=> Only write to cache on push to main

packages/dummy/README.md, packages/dummy/package.json, packages/dummy/src/index.ts
A dummy package used for release testing
=> Add dummy package

.github/workflows/save-cache.yml, .github/workflows/test.yml
**Summary:**
@havardholvik
@kevinwhereby
@nandito
@thyal
=> Add test workflows on development branch

.changeset/config.json, turbo.json
Updates ignore list to make workflow pass. Tweak caching rules to use the built-in hashing algorithm. Also cache output for the relevant tasks
=> common: Update changesets ignore + turbo cache settings

.changeset/config.json, packages/browser-sdk/package.json
This updates the ignore list and makes the browser-sdk package public.
=> common: Release

.github/PULL_REQUEST_TEMPLATE.md, README.md, package.json
**Summary:**
@havardholvik
@kevinwhereby
@nandito
@thyal
=> common: Update readme and PR template

.github/workflows/exit-prerelease.yml, .github/workflows/prerelease.yml
**Summary:**
@havardholvik
@kevinwhereby
@nandito
@thyal
=> common: Add workflows for prerelease

.github/workflows/exit-prerelease.yml, .github/workflows/prerelease.yml
**Summary:**
@havardholvik
@kevinwhereby
@nandito
@thyal
=> Merge main into development

.github/workflows/prerelease.yml
We should run `yarn changeset version` either way. 
**Summary:**
@havardholvik
@kevinwhereby
@nandito
@thyal
=> common:  Run yarn changeset version regardless if the pre file exists

.github/workflows/prerelease.yml
**Summary:**
@havardholvik
@kevinwhereby
@nandito
@thyal
=> common: Add build step in prerelease workflow

.github/workflows/exit-prerelease.yml
**Summary:**
@havardholvik
@kevinwhereby
@nandito
@thyal
=> common: Run exit-prerelease workflow on PR against main

packages/dummy/.gitignore
=> dummy: Add gitignore

packages/browser-sdk/src/lib/react/Grid/helpers/__tests__/centerGridLayout.unit.ts, packages/browser-sdk/src/lib/react/Grid/helpers/__tests__/gridUtils.unit.ts, packages/browser-sdk/src/lib/react/Grid/helpers/__tests__/stageLayout.unit.ts, packages/browser-sdk/src/lib/react/Grid/helpers/cellView.ts, packages/browser-sdk/src/lib/react/Grid/helpers/centerGridLayout.ts, packages/browser-sdk/src/lib/react/Grid/helpers/gridUtils.ts, packages/browser-sdk/src/lib/react/Grid/helpers/layout.ts, packages/browser-sdk/src/lib/react/Grid/helpers/layoutConstants.ts, packages/browser-sdk/src/lib/react/Grid/helpers/stageLayout.ts, packages/browser-sdk/src/lib/react/Grid/index.tsx, packages/browser-sdk/src/lib/react/VideoView.tsx, packages/browser-sdk/src/stories/custom-ui.stories.tsx
Add grid component from the development branch, but not export it.
**Summary:**
@havardholvik
@kevinwhereby
@nandito
@thyal
=> browser-sdk: Add grid component 

.changeset/good-moles-flash.md, packages/browser-sdk/src/lib/react/index.ts, rollup.base.config.js
Export grid component in beta release of the browser-sdk
**Summary:**
@havardholvik
@kevinwhereby
@nandito
@thyal
=> browser-sdk: Export grid component

.github/actions/notify-slack/action.yml, .github/workflows/build-test-release.yml, .github/workflows/exit-prerelease.yml
Sends a slack message whenever packages are published. 
Includes the packages that were published and the version.
Ideally I would like to include the changelog in the message as well, but that requires more work, as the changesets action does not expose this. 
**Summary:**
@havardholvik
@kevinwhereby
@nandito
@thyal
=> common: Notify slack when packages are published

.github/actions/notify-slack/action.yml
The pipeline failed, and I think I'm just missing this `shell:bash` line.
**Summary:**
@havardholvik
@kevinwhereby
@nandito
@thyal
=> common: Add shell:bash property to slack notify action

.github/workflows/e2e.yml
We are currently not caching e2e tests
**Summary:**
@havardholvik
@kevinwhereby
@nandito
@thyal
=> common: Cache e2e tests on CI

.github/actions/notify-slack/action.yml, README.md
Add a short description on how releases are done in the repo.
**Summary:**
@havardholvik
@kevinwhereby
@nandito
@thyal
=> common: Document release process

.github/actions/notify-slack/action.yml
There's some syntax errors in the action, this should fix it
**Summary:**
=> common: Fix slack action

.github/actions/notify-slack/action.yml
Last one of slack action PR's hopefully. There was something wrong with the `jq` script. This should fix it, you can test it by running in a terminal:
```bash
echo '[{"name":"@whereby.com/browser-sdk","version":"2.3.0"},{"name":"@whereby.com/core","version":"0.6.0"}]' | jq -r 'map(.name + "@" + .version) | join("\n")'
```
which should output:
```
@whereby.com/browser-sdk@2.3.0
@whereby.com/core@0.6.0
```
**Summary:**
under the terms of the MIT …
=> common: Fix slack action parsing

.github/actions/notify-slack/action.yml
JSON needs to be wrapped in quotes..
**Summary:**
=> common: wrap JSON in quotes for slack action

.changeset/two-rivers-lick.md, packages/media/package.json
Media package publish config was not set to `public`, so the release failed.
**Summary:**
=> media: Set publish config to public

.changeset/twelve-doors-swim.md, .github/actions/notify-slack/action.yml, packages/media/src/utils/types.ts
=> media: Add clientClaim to room joined payload

package.json, yarn.lock
Turborepo upgrade done with this command: `npx @turbo/codemod@latest update`
**Summary:**
=> common: Upgrade turborepo

packages/browser-sdk/package.json, packages/core/package.json, yarn.lock
Unused dependency. Should just be removed.
**Summary:**
=> common: Remove @swc/helpers dependency

.changeset/seven-badgers-agree.md, packages/media/src/webrtc/VegaRtcManager.ts
=> media: use audio settings for screenshare audio producer

package.json
This was meant to be included in #148 but somehow got lost. Use the new `eslint-config` package in root.
**Summary:**
`yarn test:lint` should pass
=> common: Use eslint-config

.changeset/bright-apes-tease.md, packages/browser-sdk/src/lib/embed/__tests__/embed.spec.ts, packages/browser-sdk/src/lib/embed/index.ts
**Summary:**
Adding attributes for aec, agc, audioDenoiser, and autoHideSelfView
N/A
N/A
N/A
-   [ x] My code follows the project's coding standards.
-   [ x] Prefixed the PR title and commit messages with the service or package name
-   [ x] I have written unit tests (if applicable).
-   [x ] I have updated the documentation (if applicable).
-   [ x] By submitting this pull request, I confirm that my contribution is made
=> browser-sdk/Levinger/attributes pt2

.changeset/curly-mangos-press.md, .changeset/warm-peaches-thank.md, packages/browser-sdk/src/lib/react/useRoomConnection/index.ts, packages/browser-sdk/src/lib/react/version.ts, packages/core/src/index.ts, packages/core/src/redux/slices/__tests__/app.unit.ts, packages/core/src/redux/slices/app.ts, packages/core/src/redux/slices/roomConnection.ts, packages/core/src/version.ts, rollup.base.config.js
**Summary:**
Fix providing userAgent data.
1. Add some console logging in `userRoomConnection` or in `doAppJoin` to print `userAgent`
2. Run the example app connect to existing embedded room (use funtimes account for example)
3. Check that correct version is printed out
=> Fix providing userAgent data

.changeset/gold-pigs-occur.md, .changeset/witty-dolls-stare.md, apps/sample-app/src/App.tsx, jest.base.config.js, package.json, packages/browser-sdk/.gitignore, packages/browser-sdk/jest.config.js, packages/browser-sdk/package.json, packages/browser-sdk/src/lib/embed/index.ts, packages/browser-sdk/src/lib/react/Grid/index.tsx, packages/browser-sdk/src/lib/react/VideoView.tsx, packages/browser-sdk/src/stories/custom-ui.stories.tsx, packages/core/.gitignore, packages/core/package.json, packages/core/rollup.config.js, packages/core/src/index.ts, packages/media/.gitignore, packages/media/package.json, packages/media/rollup.config.js, packages/media/tsconfig.build.json, turbo.json, yarn.lock
Building for node, browsers, modern bundlers and old bundlers (Webpack 4 and lower) is tricky, and our current setup works for everything expect old bundlers. This is an attempt to fix this. I've used this tool https://github.com/arethetypeswrong/arethetypeswrong.github.io to analyze the build setup, and both `core` and `media` is passing all their checks with this setup. 
The `browser-sdk` package is a bit different, we don't need to support node there f.ex.
I've also installed and added this build/type check as part of the test pipeline. This should give us some confidence going forward that we don't regress in this area. Each lib in the `package` folder has now a `test:attw` script that runs this check. This is also run as part of the normal `yarn test` script (So we check this on each …
=> common: Fix builds and set up arethetypeswrong tests

.changeset/smooth-guests-fetch.md, packages/media/src/webrtc/VegaRtcManager.ts
…ack"
This reverts commit 31090cbcc08fa998ea83e3166b0d9207b44346ab.
**Summary:**
=> media: revert "Handles recovering after trying to produce an ended track"

apps/embed-element-app/vite.config.ts, apps/quiz-app/vite.config.ts
Forgot about this when porting the example apps to vite.
**Summary:**
=> example-apps: Add process.env to vite config

.changeset/nasty-plums-perform.md, packages/core/src/redux/slices/localMedia.ts, packages/core/src/redux/tests/store/localMedia.spec.ts
**Summary:**
There was a bug in doUpdateDeviceList [(see here for more details on how to reproduce the issue)](https://linear.app/whereby/issue/PAN-1022/low-data-mode-onoff). We refactored this to match updates in PWA, which has resolved the issue 🙌 
**_You need some kind of additional microphone or camera to reproduce._** 
- Run `yarn build && yarn dev`
- Connect to http://localhost:6006/?path=/story/examples-custom-ui--room-connection-with-local-media
- Join the room in another tab as well so you can check the video stream 
- Switch to your external device (either camera or microphone is fine)
- Open dev tools console to make sure there's no issues across the next few steps
- Disconnect from the external device whilst it is still in use - eg disconnect your webcam …
=> core: refactor doUpdateDeviceList

apps/sample-app/src/App.tsx, packages/browser-sdk/src/stories/custom-ui.stories.tsx, packages/core/src/utils/fakeAudioStream.ts, packages/core/src/utils/fakeWebcamFrame.ts, packages/core/src/utils/getFakeMediaStream.ts, packages/core/src/utils/index.ts
Improve the way we provide and consume fake audio/video MediaStream in the App for testing.
**Summary:**
e2e tests should pass on PR
=> Add getFakeMediaStream util

.changeset/tall-pants-enjoy.md, packages/media/src/webrtc/rtcStatsService.ts
This adds a bit more info to be sent to rtcstats on each reconnect.
=> rtcstats: Adds some info to reconnects

.changeset/young-singers-smell.md, packages/core/src/redux/slices/signalConnection/index.ts
-------
**Summary:**
export signal events from core so we can subscribe to them in the captioner worker
https://linear.app/whereby/issue/COB-695/clean-up-deepgram-sockets-when-participants-leave
=> core: export signal events

package.json, yarn.lock
=> common: Bump turborepo

.changeset/orange-cycles-smile.md, packages/browser-sdk/src/lib/embed/index.ts
**Summary:**
Add support for leave meeting command
Relient on this PWA PR: https://github.com/whereby/pwa/pull/4078
=> browser-sdk: Add leave meeting command to embed element

.changeset/cyan-lemons-hang.md, packages/media/src/webrtc/VegaRtcManager.ts
This transfers any feature prefixed by sfu to the sfu server
=> media: Transfers features from manager to sfu

.changeset/dry-mirrors-promise.md, packages/browser-sdk/src/lib/embed/__tests__/embed.spec.ts, packages/browser-sdk/src/lib/embed/index.ts
add callQualityMonitoring attribute
N/A
This is a typechange, tests are included in src/lib/embed/__tests__
-   [x ] My code follows the project's coding standards.
-   [ x] Prefixed the PR title and commit messages with the service or package name
-   [x ] I have written unit tests (if applicable).
-   [x ] I have updated the documentation (if applicable).
-   [ x] By submitting this pull request, I confirm that my contribution is made
=> browser-sdk: add callQualityMonitoring attribute

.changeset/kind-dogs-smell.md, packages/media/src/webrtc/Session.ts
**Summary:**
Based on a reoccurring issue seen in Sentry, I'm adding tracking to be able to investigate it better.
I'm also removing some old debug code, because Odin is telling me to do so.
=> Add tracking for replace track issue in P2P

.changeset/pretty-clocks-battle.md, packages/media/src/webrtc/P2pRtcManager.ts, packages/media/src/webrtc/VegaRtcManager/index.ts, packages/media/src/webrtc/types.ts
**Summary:**
Test instructions in PWA
I left console.logs in the code for reviewer to be able to test it easily.
=> Improve track ended event listeners

.changeset/silver-bats-suffer.md, packages/core/src/redux/slices/signalConnection/actions.ts, packages/core/src/redux/slices/signalConnection/index.ts, packages/media/src/model/protocol.ts, packages/media/src/utils/types.ts
**Summary:**
Exposed session transcription events.
=> Add live transcription events

package.json, turbo.json, yarn.lock
Upgrade turbo dependency 
**Summary:**
=> common: Upgrade turbo dependency

.changeset/chilly-plums-float.md, packages/media/package.json, packages/media/src/webrtc/VegaConnection.ts, packages/media/src/webrtc/VegaRtcManager/__tests__/index.spec.ts, packages/media/src/webrtc/VegaRtcManager/index.ts, packages/media/tests/webrtc/webRtcHelpers.ts, yarn.lock
=> media: update replace webcam track in vega rtcmanager

packages/media/src/model/protocol.ts
=> media: Remove sfu_token const

.changeset/seven-jeans-boil.md, packages/media/package.json, yarn.lock
Updates rtcstats to 5.4.1 to fix some time discrepancies in analytics
Not sure what's up with the yarn.lock change. Improved format?
=> Updates rtcstats to 5.4.1

.changeset/wicked-pans-sort.md, packages/media/src/webrtc/Session.ts
=> Remove debug in p2p replace track function

.changeset/hip-carpets-push.md, packages/media/src/webrtc/stats/IssueMonitor/index.ts, packages/media/src/webrtc/stats/StatsMonitor/metrics.ts
This adds turn metrics to stats
=> Adds turn metrics

.changeset/little-starfishes-cover.md, packages/media/src/webrtc/stats/StatsMonitor/collectStats.ts
=> Handle track change when mediasourceid is missing in rtcstatsreport

.changeset/early-buckets-decide.md, packages/browser-sdk/src/lib/embed/index.ts
**Summary:**
Support start and stop transcription commands for the embed element 🗣️ 
Test with this PWA PR: https://github.com/whereby/pwa/pull/4183
I think the quickest way to test is to add some start / stop buttons to the prebuilt UI story on storybook!
1. Add some buttons to **prebuilt-ui-stories** - for example
`<button onClick={() => elmRef.current?.startLiveTranscription()}>Start transcription</button>
<button onClick={() => elmRef.current?.stopLiveTranscription()}>Stop transcription</button>`
2. run `yarn build && yarn dev`
3. Visit an room with live transcriptions enabled (can do via the org dashboard eg `https://embedded-ip-127-0-0-1.hereby.dev:4443/org/settings/transcription`. ) Set the trigger to manual, and make sure `liveTranscriptionsOn` flag is enabled …
=> browser-sdk: support start and stop transcription commands

.changeset/hot-socks-mix.md, packages/media/src/utils/ReconnectManager.ts, packages/media/src/utils/ServerSocket.ts, packages/media/src/webrtc/VegaConnection.ts, packages/media/src/webrtc/VegaRtcManager/index.ts
=> Consider signal connection state on SFU reconnect

.changeset/yellow-cheetahs-fly.md, packages/react-native-sdk/CHANGELOG.md, packages/react-native-sdk/package.json
Publish access needs to be public. 
**Summary:**
=> react-native-sdk: Change publish config access to public

.changeset/clean-buckets-admire.md, apps/react-native-webview-example/app/room/index.tsx, packages/react-native-sdk/package.json, packages/react-native-sdk/src/embed/index.tsx
Adds attributes/preferences to the embed element. For now it's just copied over from the browser-sdk embed element, but this should be moved to the core package so that it can be reused across both libraries.
**Summary:**
=> react-native-sdk: Add attributes to WherebyEmbed component

.changeset/shy-poets-teach.md, packages/media/src/utils/ReconnectManager.ts, packages/media/src/utils/ServerSocket.ts, packages/media/src/webrtc/VegaConnection.ts, packages/media/src/webrtc/VegaRtcManager/index.ts
This reverts commit b5adf9db209014ec5f12d05f43dc4e9107f78851.
**Summary:**
=> Revert "media: consider signal connection state on sfu reconnect (#367)"

apps/embed-element-app/package.json, apps/nextjs-example/package.json, apps/quiz-app/package.json, apps/react-native-webview-example/package.json, apps/sample-app/package.json, apps/telehealth-tutorial-app/package.json, package.json, packages/browser-sdk/package.json, packages/core/package.json, packages/media/package.json, packages/react-native-sdk/package.json, turbo.json, yarn.lock
🧹  Adds `yarn clean`. Just an easy way to remove all `node_modules` and turbo folders. Sometimes you need to reinstall stuff, and it's painful to go through app-by-app. 
**Summary:**
Run `yarn clean`
=> common: Add clean command

.changeset/rotten-eggs-appear.md, packages/media/src/utils/types.ts, packages/media/src/webrtc/P2pRtcManager.ts, packages/media/tests/webrtc/P2pRtcManager.spec.ts
=> Enable enforcing turn transport protocol in p2p

.changeset/hip-goats-kiss.md, packages/media/src/utils/ReconnectManager.ts, packages/media/src/utils/ServerSocket.ts, packages/media/src/webrtc/VegaConnection.ts, packages/media/src/webrtc/VegaRtcManager/index.ts
=> Add SfuReconnectV2 experiment

.changeset/itchy-gifts-deny.md, packages/browser-sdk/src/lib/react/useRoomConnection/index.ts, packages/browser-sdk/src/lib/react/useRoomConnection/types.ts, packages/browser-sdk/src/stories/components/VideoExperience.tsx, packages/core/src/redux/slices/__tests__/authorization.unit.ts, packages/core/src/redux/slices/authorization.ts, packages/core/src/redux/slices/chat.ts, packages/core/src/redux/slices/cloudRecording.ts, packages/core/src/redux/slices/localMedia.ts, packages/core/src/redux/slices/localParticipant.ts, packages/core/src/redux/slices/localScreenshare.ts, packages/core/src/redux/slices/notifications/events.ts, packages/core/src/redux/slices/notifications/index.ts, packages/core/src/redux/slices/remoteParticipants.ts, packages/core/src/redux/slices/rtcAnalytics.ts, packages/core/src/redux/slices/signalConnection/actions.ts, packages/core/src/redux/slices/signalConnection/index.ts, packages/core/src/redux/slices/waitingParticipants.ts, packages/core/src/redux/tests/store.setup.ts, packages/core/src/redux/tests/store/chat.spec.ts, packages/core/src/redux/tests/store/cloudRecording.spec.ts, packages/core/src/redux/tests/store/localParticipant.spec.ts, packages/core/src/redux/tests/store/localScreenshare.spec.ts, packages/core/src/redux/tests/store/remoteParticipants.spec.ts, packages/core/src/redux/tests/store/waitingParticipants.spec.ts, packages/core/src/redux/thunk.ts, packages/media/src/utils/types.ts
Add the possibility for hosts to turn off cameras for remote participants. The action turnOffParticipantCameras takes an array of clientIds, so you can also implement "turn off all cameras" functionality with this. Also adds `askToTurnOnCamera` function, that a host can use to ask a participant to enable their camera.
**Summary:**
1. Check out this branch
2. In the /.env file add a valid host roomKey for the configured STORYBOOK_ROOM in following line:
STORYBOOK_ROOM_HOST_ROOMKEY=[host_roomKey_here]
3. Run yarn build && yarn dev
4. In the Storybook UI (@ http://localhost:6006/) open the story: "Custom UI" > "Room Connection With Host Controls"
5. Join the same room in a different browser (PWA).
6. Clicking on the turn off camera button on the remote participant should …
=> common: Turn remote camera off/ask to turn camera on

.changeset/giant-donkeys-double.md, packages/media/src/webrtc/VegaConnection.ts, packages/media/src/webrtc/VegaRtcManager/index.ts
=> Avoid sfu reconnect loop

.changeset/forty-queens-suffer.md, packages/media/src/utils/Logger.ts, packages/media/src/webrtc/stats/IssueMonitor/__tests__/packetLossAnalyser.spec.ts, packages/media/src/webrtc/stats/IssueMonitor/issueDetectors.ts, packages/media/src/webrtc/stats/IssueMonitor/packetLossAnalyser.ts
=> Add periodic packet loss detection

.changeset/wet-jobs-grab.md, packages/media/src/webrtc/stats/IssueMonitor/__tests__/packetLossAnalyser.spec.ts, packages/media/src/webrtc/stats/IssueMonitor/issueDetectors.ts, packages/media/src/webrtc/stats/IssueMonitor/packetLossAnalyser.ts
**Summary:**
* Support invalidating periodic packet loss issue if previous interval is exceeded.
* Make debug logs be at debug level
=> Support additional scenario in packet loss analyser

.changeset/wise-flies-fold.md, packages/media/src/webrtc/stats/IssueMonitor/__tests__/packetLossAnalyser.spec.ts, packages/media/src/webrtc/stats/IssueMonitor/packetLossAnalyser.ts
=> Improve periodic packet loss detection

.changeset/tricky-starfishes-tease.md, packages/media/src/utils/mediaSettings.ts, packages/media/src/webrtc/P2pRtcManager.ts, packages/media/src/webrtc/VegaRtcManager/index.ts
=> Add low bandwidth mode

.changeset/giant-squids-jam.md, packages/media/src/webrtc/stats/IssueMonitor/__tests__/issueDetectors.spec.ts, packages/media/src/webrtc/stats/IssueMonitor/__tests__/packetLossAnalyser.spec.ts, packages/media/src/webrtc/stats/IssueMonitor/index.ts, packages/media/src/webrtc/stats/IssueMonitor/issueDetectors.ts, packages/media/src/webrtc/stats/IssueMonitor/packetLossAnalyser.ts, packages/media/src/webrtc/stats/StatsMonitor/collectStats.ts, packages/media/src/webrtc/stats/StatsMonitor/index.ts
=> Add typing to stats collection

.changeset/green-moons-trade.md, .github/workflows/e2e.yml, packages/media/src/webrtc/stats/IssueMonitor/index.ts, packages/media/src/webrtc/stats/StatsMonitor/__tests__/index.spec.ts, packages/media/src/webrtc/stats/StatsMonitor/collectStats.ts, packages/media/src/webrtc/stats/StatsMonitor/index.ts
=> Add tracking for failed stats report parsing

.changeset/silly-pugs-enjoy.md, packages/media/package.json, packages/media/src/webrtc/P2pRtcManager.ts, yarn.lock
=> media: update dependencies

.changeset/flat-pots-run.md, packages/core/src/redux/slices/localMedia.ts, packages/core/src/redux/tests/store/localMedia.spec.ts, packages/media/src/webrtc/MediaDevices.ts, packages/media/src/webrtc/types.ts, packages/media/tests/webrtc/MediaDevices.spec.ts
=> media: expose removed devices in getupdateddevices

.changeset/fifty-queens-serve.md, packages/media/src/webrtc/RtcManagerDispatcher.ts, packages/media/src/webrtc/stats/IssueMonitor/issueDetectors.ts
=> media: fix quality-limitation-bw p2p audio-only

.changeset/large-pugs-explode.md, packages/media/src/webrtc/BandwidthTester.ts
=> media: fix bwtester sfu url

packages/browser-sdk/README.md
-------
**Summary:**
just a quick readme update showing the v3 api on the browser-sdk readme after some feedback in the support Discord
https://linear.app/whereby/issue/PAN-1442/update-react-sdk-docs
=> browser-sdk: add v3 changes to README

.changeset/violet-socks-arrive.md, packages/media/src/webrtc/BandwidthTester.ts
=> media: handle failed sfu connection in bwtester

.changeset/wise-tables-allow.md, packages/media/src/utils/__tests__/mediaSettings.spec.ts, packages/media/src/utils/mediaSettings.ts, packages/media/src/webrtc/P2pRtcManager.ts, packages/media/tests/webrtc/P2pRtcManager.spec.ts
**Summary:**
Adds a flag to control sorting video codecs by hardware decodability
https://linear.app/whereby/issue/COB-1630/orderfilter-codecs-by-powerefficiencyhardware-decoder
1. checkout this PWA branch: https://github.com/whereby/pwa/pull/4325
1. join a P2P room from a chrome and safari client, open chrome://webrtc-internals and make note of the order of the video codecs in the offer. You can also add `?stats` to see the codec used
1. add `&preferHardwareDecodingOn` flag
1. check the codecs in the offer, they should have changed order
1. if you like, check the hardware decodability of the top and bottom codecs like so:
```javascript
const { powerEfficient } = await navigator.mediaCapabilities.decodingInfo({
type: "webrtc",
video: {
width: 1280,
height: 720,
bitrate: …
```
=> media: Sort codecs by power efficiency

.changeset/bright-friends-grow.md, packages/media/package.json, pnpm-lock.yaml
It's an unused dependency
**Summary:**
=> Remove ua-parser-js

.changeset/cool-experts-serve.md, packages/media/src/utils/types.ts
=> media: Add assistant-related errors to `RoomJoinedErrors` type definition
