whereby/sdk

apps/embed-element-app/.gitignore
apps/embed-element-app/index.html
apps/embed-element-app/package.json
apps/embed-element-app/src/react-app-env.d.ts
apps/embed-element-app/tsconfig.json
apps/embed-element-app/vite-env.d.ts
apps/embed-element-app/vite.config.ts
apps/quiz-app/.gitignore
apps/quiz-app/index.html
apps/quiz-app/package.json
apps/quiz-app/tsconfig.json
apps/quiz-app/vite-env.d.ts
apps/quiz-app/vite.config.ts
apps/telehealth-tutorial-app/.gitignore
apps/telehealth-tutorial-app/index.html
apps/telehealth-tutorial-app/package.json
apps/telehealth-tutorial-app/tsconfig.json
apps/telehealth-tutorial-app/vite-env.d.ts
apps/telehealth-tutorial-app/vite.config.ts
yarn.lock

CRA is not maintained any more, and has some vulnerabilities. Move all the example apps to vite instead.
`yarn audit` on main:
```
2 vulnerabilities found - Packages audited: 1792
Severity: 1 Moderate | 1 High
```
on this branch:
```
0 vulnerabilities found - Packages audited: 939
```
**Summary:**
Run the example apps: they should start
@havardholvik
@kevinwhereby
@nandito
@thyal

Replace CRA with vite for example apps

---

.github/actions/deploy-cdn/action.yml
.github/workflows/build-test-release.yml

This adds a new step to the build-test-release workflow that will deploy the cdn build output to our CloudFront distribution.

Add CDN deploy step to build-test-release workflow

---

.changeset/fuzzy-crews-smoke.md
packages/browser-sdk/src/lib/core/redux/slices/rtcAnalytics.ts

We are not passing `roomSessionId` to RTC stats if it changes during a call. That's why we have the bug where we only have insights for SDK clients that joins a room with another client already in the room.
**Summary:**
- Pass `roomSessionId` to RTC stats whenever it changes.
1. Start local-stack with aws-vault
2. Go to storybook on this branch, and go to a story (room connection only, f.ex)
3. Join the same room with another client
4. Stay in the room for a couple of minutes
5. Leave with both clients
6. Go to the dashboard -> insights
7. Find the session (the last one)
8. Find the SDK client, click on the insight page for that client
9. Verify that there are insights.
-   [ ] I have written unit tests (if …

Pass roomSessionId to RTCStats whenever it changes

---

.changeset/six-rabbits-poke.md
packages/browser-sdk/src/lib/core/redux/slices/__tests__/app.unit.ts
packages/browser-sdk/src/lib/core/redux/slices/app.ts

SSR apps render in node, so this doesn't work. We'll explicitly pass `{
app: { isNodeSdk } }` to `createStore` when needed

remove detection of node environment

---

.changeset/gentle-walls-thank.md
packages/browser-sdk/package.json

This was missed when moving the package over from
the old repository.

browser-sdk: Update repo url in package.json

---

.changeset/weak-pugs-push.md
packages/browser-sdk/src/lib/__mocks__/MediaStream.ts
packages/browser-sdk/src/lib/core/redux/slices/localMedia.ts
packages/browser-sdk/src/lib/core/redux/tests/store/localMedia.spec.ts

This fixes a bug which prevented us from stopping the video tracks when the camera was disabled.
1. `yarn dev`
2. In "roomConnection with local media", connect to a room
3. Toggle camera, verify light goes off.
4. Toggle back on, ensure video is flowing.
5. Leave room, ensure camera light stays on.

browser-sdk: Stop video tracks when disabling camera

---

.github/workflows/exit-prerelease.yml

Some changes to the exit prerelease flow:
* If the pre.json file exists on a PR to main,
* we run `yarn changeset pre exit` on the branch (development)
* This will edit the pre.json file, but not remove it. 
* Then it's merged in to main
* `yarn changeset version` will run on push to main
* A new PR will be opened with correct version bumps, and the pre.json will be removed.
**Summary:**
@havardholvik …

common: Adjust exit prerelease workflow

---

.changeset/rotten-years-refuse.md
packages/core/package.json
yarn.lock

Some users have problems installing our browser-sdk, being presented with an error when trying to install the auto-config devDependency in jslib-media. This change removes this dependency, hopefully resolving the issue.

core: Update jslib-media to prevent install errors

---

.changeset/brave-eagles-rest.md
apps/embed-element-app/src/App.tsx
packages/browser-sdk/src/lib/embed/index.ts

**Summary:**
Adding documentation of the `people_toggle` event listener.
https://linear.app/whereby/issue/PAN-825/add-event-listener-for-people-button-to-whereby-embed
https://github.com/whereby/pwa/pull/3912
Will create a changeset after the first release goes out later.
@thyal

browser-sdk: Add peopleToggle to types and examples

---

.changeset/tasty-geese-sit.md
packages/core/src/redux/slices/__tests__/roomConnection.unit.ts
packages/core/src/redux/slices/roomConnection.ts

-------
**Summary:**
Currently for any error except `room_locked`, the SDK thinks it joins
the room successfully. Rather than explicily handle all possible errors,
we can fall back to this handler and add more specific cases as they are
required by the SDK
https://linear.app/whereby/issue/COB-522/auto-stop-captioner
We need to know if the room join fails, so we can kill the captioning process
To see the error, make a small room and try to join it with 5 SDK clients. using the example apps If you keep an eye on the room connection status you'll see it says 'connected' for all clients even though the 5th is refused entry due to "room_full"
Now build this branch and run the same test, you'll see the last client changes it's roomConnectionStatus to 'disconnected' and sets …

core: handle room_joined errors

---

.changeset/heavy-carrots-sort.md
packages/core/src/redux/slices/__tests__/remoteParticipants.unit.ts
packages/core/src/redux/slices/__tests__/roomConnection.unit.ts
packages/core/src/redux/slices/__tests__/waitingParticipants.unit.ts
packages/core/src/redux/slices/localParticipant.ts
packages/core/src/redux/slices/roomConnection.ts
packages/core/src/types.d.ts

Store the client claim returned from the server when joining a room and send it back in any subsequent room joining request.

core: Return client claim when joining a room

---

.changeset/clean-pumas-know.md
packages/core/src/redux/slices/__tests__/roomConnection.unit.ts
packages/core/src/redux/slices/__tests__/signalConnection.unit.ts
packages/core/src/redux/slices/roomConnection.ts
packages/core/src/redux/slices/signalConnection/index.ts

-------
**Summary:**
The signal socket emits a 'disconnect' event when it loses connection
with the server - i.e. when the network is lost
We should update the signalConnection status and roomConenction status
when this happens
https://linear.app/whereby/issue/COB-522/auto-stop-captioner
On main, open a room in an SDK client. Turn off your network to disconnect from Signal and keep an eye on the signal/roomConnection status and Redux events. After about 30 seconds there will be a `disconnect` event from signal, but the SDK will think signal and room connection are still `connected`
Do the same on this branch and see the roomConnection and signalConnection status to update to `disconnected`
-   [x] Prefixed the PR …

core: handle signal disconnect events

---

.github/workflows/canary-release.yml
README.md

Adds workflow for canary releases. It's not done automatically, but on demand. You can simply add a changeset like normal, and comment `/canary` or `/canary-release` on the PR to create one.
**Summary:**

common: Add workflow for canary releases

---

.changeset/rare-jars-listen.md
packages/media/src/webrtc/VegaRtcManager.ts

**Summary:**
This handles a part of the close/open lid issue and possibly other cases. When trying to produce an ended track, mediasoup client will throw and the producer would not be created. Whenever this happens, it will usually be replaced by a working track later - so we need to make sure the producer is created then. 
When closing the lid on some/all machines/browsers, the track will end, and the SFU websocket will be closed. After opening the lid again, if the websocket is re-established before the track is replaced (always on my chrome@mac), it would fail.
[](https://linear.app/whereby/issue/COB-517/handle-closing-and-opening-lid)
Testing instruction will be in PWA PR, as some changes are needed there as well.

media: Handles recovering after trying to produce an ended track

---

.changeset/mean-seas-battle.md
packages/browser-sdk/.storybook/main.cjs
packages/core/package.json
packages/media/package.json

Apparently `default` property in package.json needs to come last 🙄 Storybook complained about this and wouldn't start. 
Don't think this makes a difference in node/webpack 4, so I don't think it's necessary to bump versions here.
**Summary:**
`yarn dev` <- Storybook should start as normal

common: Fix storybook

---

.changeset/fresh-queens-fly.md
packages/media/src/webrtc/VegaRtcManager.ts

This should fix recent regression introduced by close/open lid fix (https://github.com/whereby/sdk/pull/142). Instead of avoiding producing non-live tracks, we should avoid producing ended tracks.

media: allow creating producers for track not live yet

---

.changeset/fresh-steaks-arrive.md
.changeset/small-trains-tan.md
packages/core/src/redux/slices/__tests__/remoteParticipants.unit.ts
packages/core/src/redux/slices/remoteParticipants.ts

**Summary:**
* Replace the `MediaStream.getAudioTracks().length > 0` with a `MediaStream.getTrack().some()` function, as some WebRTC implementation does not have `.getAudioTracks()` implemented.
* Use fallback ids if the MediaStream has no `id` for screenshares: `pres-<clientId>` for remote participants and `local-screenshare` for local participant.
1. Start screenshare with and without audio
2. They should work as before
under the terms of the MIT …

core: use getTrack().some() to tell if screenshare has audio and use fallback id

---

.changeset/witty-masks-attend.md
packages/media/src/webrtc/VegaRtcManager.ts

**Summary:**
Wait for send transport before trying to produce a video track
Also move initial sync code outside of async function

media: wait for sendtransport before producing

---

.changeset/wise-crabs-refuse.md
packages/media/jest.config.js
packages/media/src/webrtc/stats/IssueMonitor/__tests__/index.spec.ts
packages/media/src/webrtc/stats/IssueMonitor/__tests__/issueDetectors.spec.ts
packages/media/src/webrtc/stats/IssueMonitor/index.ts
packages/media/src/webrtc/stats/IssueMonitor/issueDetectors.ts
packages/media/src/webrtc/stats/types.ts

With audio-only mode, this issue detector incorrectly detected dry-track, bad-network, no-track, and no-track-stats when in p2p. This fixes the issue by taking the audio-only mode state of other clients into account.
Also extracted the issue detectors into their own file and added a test suite, along with some initial types.
Check out the following branches and restart local-stack:
- https://github.com/whereby/video-conference/pull/14844
- https://github.com/whereby/pwa/pull/4024
For both a P2P and SFU room, check the following
1. Join <room-url>?audioOnlyExperimentOn x 2
2. For both participants, start `!stats` in chat
3. For one particpant, enable audio-only mode
4. For the other participant, verify you DONT have `bad-network`, `dry-track`, `no-track`, `no-track-stats` issues
5. Test in …

media: Fix broken issue detectors

---

.changeset/new-eels-tease.md
packages/core/src/redux/slices/signalConnection/index.ts
packages/core/src/redux/tests/store/signalConnection.spec.ts

During testing we discovered that the process of reconnecting to a room after network disconnect/reconnect was broken.
This PR fixes the reconnect flow and reuses the existing device credentials from the original signal connection.
1. Join the room URL configured in the SDK from the room URL (not using the SDK) to observe the following steps.
2. **Using `master` branch**, run `yarn dev`
3. Navigate to the "Room Connection Only" storybook page in the browser. SDK should join the configured room.
4. In the Developer Tools, simulate a network disconnect and network reconnect (i.e. switch from "No throttling" to "Offline" and then after a couple of seconds switch back to "No throttling")
5. The SDK is unable to reconnect to the room on network reconnect and `RTCPeerConnection` warnings are …

core: Fix signal reconnect flow

---

.changeset/moody-mice-behave.md
packages/browser-sdk/src/lib/react/useLocalMedia/index.ts
packages/browser-sdk/src/lib/react/useLocalMedia/types.ts
packages/browser-sdk/src/lib/react/useRoomConnection/index.ts
packages/browser-sdk/src/lib/react/useRoomConnection/types.ts
packages/browser-sdk/src/stories/components/VideoExperience.tsx
packages/core/src/redux/slices/localMedia.ts
packages/core/src/redux/slices/rtcConnection/index.ts
packages/core/src/redux/tests/store/localMedia.spec.ts

**Summary:**
Enable toggling low data mode ✨ 
- Run yarn build && yarn dev
- Connect to http://localhost:6006/?path=/story/examples-custom-ui--room-connection-with-local-media
- Join the room in another tab as well so you can check the video stream
- Toggle low data mode
- Check that the stream is still active in the other tab! 
- In redux tab of dev tools, you can check that low data mode is toggling on / off properly
under the terms of the MIT …

common: toggle low data mode

---

.changeset/wicked-goats-notice.md
packages/browser-sdk/src/lib/react/useRoomConnection/index.ts
packages/browser-sdk/src/lib/react/useRoomConnection/types.ts
packages/browser-sdk/src/stories/components/VideoExperience.tsx
packages/browser-sdk/vite.config.mts
packages/core/src/redux/index.ts
packages/core/src/redux/slices/__tests__/authorization.unit.ts
packages/core/src/redux/slices/__tests__/room.unit.ts
packages/core/src/redux/slices/authorization.ts
packages/core/src/redux/slices/localParticipant.ts
packages/core/src/redux/slices/room.ts
packages/core/src/redux/slices/roomConnection.ts
packages/core/src/redux/slices/rtcAnalytics.ts
packages/core/src/redux/store.ts
packages/core/src/redux/tests/store/authorization.spec.ts
packages/core/src/redux/tests/store/remoteParticipants.spec.ts
packages/core/src/redux/tests/store/room.spec.ts

Allow participants joining with the `host` role to kick a remote participant and/or end the meeting for all remote participants.
1. Run local-stack and join a room with 1 or more participants via PWA.
2. Check out this branch
3. Ensure that STORYBOOK_ROOM is the same URL as the joined room in step 1.
4. In the `/.env` file add a valid _host_ `roomKey` for the configured `STORYBOOK_ROOM` in following line:
```
STORYBOOK_ROOM_HOST_ROOMKEY=[host_roomKey_here]
```
5. Run `yarn build && yarn dev`
6. Open the storybook story: "Custom UI" > "Room Connection With Host Controls" ([direct localhost link](http://localhost:6006/?path=/story/examples-custom-ui--room-connection-with-host-controls))
7. Check that the `roomKey` is filled with the host room key added in step 4.
8. Clicking on the "End …

Add kick participant and end meeting actions for meeting hosts

---

.github/workflows/e2e.yml

An attempt to fix the e2e tests. The only difference from the previous passing tests is the `macos-latest` has changed from `macos-12` to `macos-14-arm64`. Let's see if reverting back to 12 fixes the issues 
**Summary:**
e2e tests should pass

e2e: Change e2e test runner to macos-12

---

.github/workflows/e2e.yml

e2e tests are failing and it would be useful to see the playwright report. We missed this when switching to the monorepo, so the folder path is wrong and therefore no report is uploaded currently.
**Summary:**

e2e: Use correct playwright-report folder path

---

packages/browser-sdk/package.json
packages/browser-sdk/src/lib/react/Grid/index.tsx
packages/browser-sdk/src/lib/react/Grid/useGrid.ts
packages/browser-sdk/src/lib/react/Provider/hooks.ts
packages/browser-sdk/src/lib/react/Provider/index.tsx
packages/browser-sdk/src/lib/react/VideoView.tsx
packages/browser-sdk/src/lib/react/useLocalMedia/index.ts
packages/browser-sdk/src/lib/react/useLocalMedia/types.ts
packages/browser-sdk/src/lib/react/useRoomConnection/index.ts
yarn.lock

Use `react-redux` hooks instead of the custom `observeStore` setup we have currently. This is a more traditional redux setup, and since we now have a provider, it allows us to do this instead. 
Instead of calling `observeStore()` and passing in selectors, we can now simply use `useAppSelector` and `useAppDispatch` with full store access in any component.
**Summary:**
Regression testing

browser-sdk: Redux hooks

---

.changeset/tame-frogs-sparkle.md
packages/browser-sdk/src/lib/react/useRoomConnection/index.ts
packages/browser-sdk/src/lib/react/useRoomConnection/types.ts
packages/browser-sdk/src/stories/components/VideoExperience.tsx
packages/browser-sdk/src/stories/custom-ui.stories.tsx
packages/core/src/redux/slices/room.ts
packages/core/src/redux/tests/store/room.spec.ts

Add a "stay behind" option for a host invoking the `endMeeting` action to opt-out of also leaving the room.
1. Ensure that a "host" roomKey is configured in the `.env` file as `STORYBOOK_ROOM_HOST_ROOMKEY`
2. Run `yarn build && yarn dev`
3. Navigate to the "Room Connection With Host Controls" story (direct link once `yarn dev` is running [here](http://localhost:6006/?path=/story/examples-custom-ui--room-connection-with-host-controls))
4. Locate the storybook control called "Stay behind after triggering meeting end" and make sure it is **unchecked** (see screenshot)
5. Click on the "End meeting" button. 
6. All remote participants should be removed from the meeting and the current host participant should also leave the meeting.
8. Reload the storybook story
9. Again locate the storybook …

common: Add `stayBehind` parameter to `endMeeting` host room action

---

.changeset/pink-fireants-shout.md
packages/browser-sdk/src/lib/embed/index.ts

**Summary:**
Updates Embed element portion of the SDK to allow for an end_meeting command/browser method
Local user must be a host
**Related PR:**
https://github.com/whereby/pwa/pull/4067

browser-sdk: Add endMeeting() command to embed element

---

.changeset/early-pugs-tan.md
apps/sample-app/src/App.tsx
apps/sample-app/test/testsuites/connect.spec.ts
packages/browser-sdk/src/lib/react/useRoomConnection/index.ts
packages/browser-sdk/src/stories/components/VideoExperience.tsx
packages/core/src/redux/slices/__tests__/app.unit.ts
packages/core/src/redux/slices/__tests__/authorization.unit.ts
packages/core/src/redux/slices/app.ts
packages/core/src/redux/slices/authorization.ts
packages/core/src/redux/slices/localMedia.ts
packages/core/src/redux/slices/localParticipant.ts
packages/core/src/redux/slices/roomConnection.ts
packages/core/src/redux/slices/signalConnection/index.ts
packages/core/src/redux/store.ts
packages/core/src/redux/tests/store/signalConnection.spec.ts

In https://github.com/whereby/sdk/pull/232, as part of adding the ability to re-join rooms, we added a mechanism to reset the core redux store state on signal disconnect. It would be better if we only cleared the core state if/when a subsequent `joinRoom()` API request is made.
This ensures that the exit state of the redux store can remain intact until it needs to be reset again to rejoin a room.
1. Run `yarn build && yarn dev`
2. Open the "Room Connection only" storybook URL (direct link when storybook is running is [here](http://localhost:6006/?path=/story/examples-custom-ui--room-connection-only)).
3. Click "Leave Room" button
4. The UI should display a single button called "Re-join left room". Clicking on this button should rejoin the room successfully.
5. Reload the "Room Connection …

core: Delay resetting the core redux store state until the next joinRoom() API request

---

.changeset/seven-crabs-know.md
apps/sample-app/src/App.tsx
packages/browser-sdk/src/lib/react/useRoomConnection/index.ts
packages/browser-sdk/src/stories/components/VideoExperience.tsx
packages/browser-sdk/src/stories/custom-ui.stories.tsx

**BREAKING CHANGE: v2 -> v3**
In browser-sdk version 3 we will stop auto-joining room sessions on invocation of the `useRoomConnection` hook itself. 
The primary motivation for this change, which will affect all users of version <= 2, is for developers to have control on when _billiable events_ (such as joining and leaving rooms and, therein, the consumption of billable participant minutes) occur in the lifecycle of their products.
In version 2, the room session would be joined automatically when creating the hook.
```javascript
/* browser-sdk version 2 */
// Joins room automatically on load
useRoomConnection(roomUrl, roomOptions);
```
In version 3, the room session will not be joined automatically when creating the hook. Instead we need to subsequently invoke the `actions.joinRoom` …

browser-sdk: Remove auto-join to room sessions when invoking useRoomConnection hook

---

.changeset/witty-fans-knock.md
packages/core/src/redux/slices/__tests__/remoteParticipants.unit.ts
packages/core/src/redux/slices/remoteParticipants.ts
packages/media/src/utils/types.ts

When invalid characters are provided in the display name the change is rejected by the signal server. This PR gracefully handles errors returned when updating client metadata instead of throwing: `Cannot destructure property 'clientId' of 'action.payload.payload' as it is undefined.`.
1. Check out `main` branch (to verify the problem first)
2. `yarn build && yarn dev`
3. Open the "Room Connection Only" story (direct link when storybook is running is [here](http://localhost:6006/?path=/story/examples-custom-ui--room-connection-only))
4. In the 'Display name' form field enter a value that includes one or more of the invalid characters for this field e.g. `$!<>:;`. Click "Save" button next to this form field.
5. An error will be displayed in the developer console: `Cannot destructure …

core: Handle case when invalid characters are provided in display name

---

.changeset/heavy-maps-pretend.md
packages/browser-sdk/src/lib/react/Grid/index.tsx
packages/browser-sdk/src/lib/react/Grid/useGrid.ts
packages/browser-sdk/src/lib/react/Grid/useGridParticipants.ts
packages/browser-sdk/src/stories/custom-ui.stories.tsx

A couple of small things I think was lost during the rebase from development into main:
* Screenshares are showing twice
* Aspect ratio reporting is looping (so just disable it for now)
* VideoGridGap prop is not passed to the grid engine
**Summary:**

browser-sdk: Fix small grid UI bugs

---

apps/quiz-app/src/views/Game/index.tsx
apps/telehealth-tutorial-app/src/App.tsx

In SDK v3 we now require apps to invoke `actions.joinRoom` after invoking the `useRoomConnection` hook.
We had a couple of test apps that were missing an update that called this action on mount. This PR ensures all the test apps continue to work in the same way as in version 2.
1. Running the `telehealth-tutorial-app` test application (`cd apps/telehealth-tutorial-app && yarn dev`) should automatically connect to the configured room.
2. Running the `quiz-app` test application (`cd apps/quiz-app && yarn dev`) should automatically connect to the configured room.
-   [ ] I have updated the documentation …

common: Add joinRoom/leaveRoom actions to all test apps

---

.changeset/mighty-tools-destroy.md
.changeset/spotty-cougars-divide.md
packages/media/src/utils/__tests__/originTrial.spec.ts
packages/media/src/utils/originTrial.ts
packages/media/src/webrtc/stats/StatsMonitor/__tests__/cpuObserver.spec.ts
packages/media/src/webrtc/stats/StatsMonitor/__tests__/index.spec.ts
packages/media/src/webrtc/stats/StatsMonitor/collectStats.ts
packages/media/src/webrtc/stats/StatsMonitor/cpuObserver.ts
packages/media/src/webrtc/stats/StatsMonitor/index.ts
packages/media/src/webrtc/stats/StatsMonitor/peerConnection.ts

Adjust how we initialize the cpu pressure observer to pass sampleInterval as an option to conform with the new api.
Nothing to test here. Tests should pass
This is a small change by itself, but I have also refactored a bit the StatsMonitor to allow for easier unit testing and also breaking apart a module which had become very large.

media: set cpu sample rate correctly

---

.changeset/swift-tomatoes-sort.md
packages/media/src/webrtc/VegaRtcManager.ts

This will allow uncapped "1:1" meetings on SFU, enabled by feature flag. Testing instructions in PWA PR

media: Allows uncapped 1:1 meetings

---

.changeset/wise-flies-whisper.md
apps/embed-element-app/src/App.tsx
packages/browser-sdk/src/lib/embed/index.ts

**Summary:**
Add support for new commands: openBreakout, closeBreakout, and togglePeople. Syntax fix in toggleChat command definition 
Reliant on this PR
https://github.com/whereby/pwa/pull/4100
In sdk repo, apps/embed-element-app example
- Imported WherebyEmbedElement
- Point roomUrl to local stack/room
- adjust const elmRef = useRef<WherebyEmbedElement>(null);
- Adjust attributes in to disable minimal, and include people tab and breakout
- Add buttons testing new functions. Example:
<button onClick={ () => elmRef.current?.openBreakout()}>breakout</button>
Then in terminal: 
`yarn dev:embed-element-app `
-   [ ] I have written unit …

browser-sdk: Add toggleBreakout(), and togglePeople() to embed element

---

.changeset/chilly-kings-chew.md
packages/core/src/redux/constants.ts
packages/core/src/redux/slices/localParticipant.ts
packages/core/src/redux/slices/remoteParticipants.ts
packages/core/src/redux/slices/room.ts
packages/core/src/redux/slices/rtcConnection/index.ts

Exclude non person roles (recorder and streamer) clients from participants selector. Also adds a new selector `selectRemoteClients`, which **includes** non person roles. This is used for stream handling f.ex.
**Summary:**

core: Exclude non person roles in remote participants selector

---

.changeset/kind-years-cheer.md
apps/sample-app/src/App.tsx
packages/browser-sdk/src/lib/react/useRoomConnection/index.ts

In browser-sdk version 3 we made a change that requires users to explicitly call `actions.joinRoom()` to connect to a room (https://github.com/whereby/sdk/pull/254).
With this change it is possible that users may try to invoke other actions when they have not yet joined and been connected to a room.
This PR adds an additional wrapper around `actions` APIs that check the user is connected to room so that actions can be successfully performed.
If the browser-sdk is not currently connected to a room then a warning will be displayed in the developer console and the action will not be triggered.
1. Check out this PR branch and run `yarn build && yarn dev`
2. Check that all custom stories continue to work as expected once Storybook has loaded.
3. Deliberably try to invoke an in-room action …

browser-sdk: Prevent in-room actions from being invoked out-of-order

---

.changeset/cold-birds-sing.md
packages/core/src/redux/slices/__tests__/localMedia.unit.ts
packages/core/src/redux/slices/__tests__/roomConnection.unit.ts
packages/core/src/redux/slices/app.ts
packages/core/src/redux/slices/localMedia.ts
packages/core/src/redux/slices/roomConnection.ts
packages/core/src/redux/tests/store/rtcConnection.spec.ts

This is causing issues with the dial in worker, so let's instead add
polyfills on that side to make it work more like the browser, rather
than altering the sdk behaviour
-------
When I tried newer /core versions with the Dial In agent (it was on 0.9.1) it didn't like all the rejoin functionality we've added here.
Instead I figured it's nicer to make the node clients work as similarly to browser clients as possible, so I've polyfilled the required functionality on the node agent side and we can remove it from here
**Summary:**
I've got a PR here updating the node agents: https://github.com/whereby/recording-service/pull/419
It shouldn't effect browser clients at all
-   [x] Prefixed the PR title and commit messages …

core: remove node sdk startup logic

---

.changeset/neat-dryers-doubt.md
packages/media/src/webrtc/VegaRtcManager/__tests__/index.spec.ts
packages/media/src/webrtc/VegaRtcManager/__tests__/utils.spec.ts
packages/media/src/webrtc/VegaRtcManager/index.ts
packages/media/src/webrtc/VegaRtcManager/utils.ts

We need to start somewhere. This change breaks out the calculation of spatial and temporal layers so they can be unit tested.
Automated tests should cover this, no functional change.

media: Add test coverage for VegaRtcManager

---

.changeset/small-walls-jog.md
packages/media/src/webrtc/P2pRtcManager.ts
packages/media/src/webrtc/VegaRtcManager/index.ts
packages/media/src/webrtc/rtcManagerEvents.ts
packages/media/src/webrtc/types.ts

**Summary:**
* monitor cam track for ended event
* set delay for turning of cam to 0 ms when disabling cam and the track has ended

Handle cam track ended event

---

.changeset/new-humans-smile.md
packages/media/src/webrtc/Session.ts

**Summary:**
We iterate over all RTCRtpSenders. We expect all to have a track but the track attribute is null if the sender is not transmitting. https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/track

Handle senders without track when replacing tracks in P2P

---

.changeset/two-cherries-begin.md
packages/media/src/webrtc/VegaRtcManager/index.ts

In many cases, `updateStreamResolution` is called before the consumer is ready. In order to avoid the integrating application needing to be aware of consumer state, we now keep track of streamId and resolution and apply the correct simulcast layer when the consumer is ready.
Will provide a PWA PR with manual test instructions.

media: Fix issue with stream resolution on SFU

---

.changeset/funny-lies-end.md
packages/browser-sdk/src/lib/embed/index.ts
packages/browser-sdk/src/stories/prebuilt-ui.stories.tsx

Creates an event for "grant_device_permissions" when a user successfully allows device permissions
Creates an event for "grant_device_permissions" when a user successfully allows device permissions
This is a type change, unit tests are included in [PWA4125](https://github.com/whereby/pwa/pull/4125).
-   [ x] My code follows the project's coding standards.
-   [x ] Prefixed the PR title and commit messages with the service or package name
-   [ x] I have written unit tests (if applicable).
-   [ x] By submitting this pull request, I confirm that my contribution is made

browser-sdk: add 'grant_device_permission' embed event

---

.changeset/seven-jobs-repeat.md
packages/core/src/redux/slices/__tests__/app.unit.ts
packages/core/src/redux/slices/app.ts
packages/core/src/redux/slices/roomConnection.ts
packages/core/src/redux/tests/store/rtcConnection.spec.ts

**Summary:**
Extend the `AppConfig` with a `isDialIn` property. This can be used later to identify dial-in participants in the meeting.
1. Join your room with PWA with devtools open and inspect the redux state
2. Join the room using the `core` pkg (see example app below)
3. Inspect the `new_client` message:
* the new client's `isDialIn` should be `true` the app config's `isDialIn` was `true`
* the new client's `isDialIn` should be `false` the app config's `isDialIn` was `false` or unspecified
`new_client` with dial-in enabled:
-   [x] By …

core: add isDialIn property to the app config

---

.changeset/short-tools-worry.md
packages/core/src/RoomParticipant.ts
packages/core/src/__mocks__/appMocks.ts
packages/core/src/redux/slices/__tests__/authorization.unit.ts
packages/core/src/redux/slices/__tests__/cloudRecording.unit.ts
packages/core/src/redux/slices/__tests__/remoteParticipants.unit.ts
packages/core/src/redux/slices/localParticipant.ts
packages/media/src/utils/types.ts

-------
**Summary:**
We added this property to the signal client, so we should add it here to
make it visible to SDK clients
https://linear.app/whereby/issue/COB-927/add-dial-in-client-property-to-browser-sdk
1. if you haven't already, create a twilio account, buy a phone number in a convenient country, and add the account SID and auth token to your local stack config like so:
``` json
"twilio-account-sid": "<account sid>",
"twilio-auth-token": "<auth token>",
```
1. you'll also need an ngrok account with the auth token configured in local stack:
``` json
"ngrok-auth-token": "<auth token>",
```
1. start local stack!
1. build the dial-in image in the recording-service repo with `yarn dial-in:build-for-local-stack`
1. enable the `dialInOn` flag for your local embedded …

common: add isDialIn participant property

---

.changeset/eighty-dolphins-float.md
packages/core/src/redux/slices/__tests__/roomConnection.unit.ts
packages/core/src/redux/slices/roomConnection.ts

**Summary:**
Extend the `selectShouldConnectRoom` to check if there's a room connection error and return `false` if there is. This should prevent the `join_room` loop if the room is full.
1. Join your `normal` size room as a host
2. Fill the `.env` file with your local-stack endpoints to test against local-stack
3. Build things `yarn build`
5. Start the sample app: `yarn dev:sample-app`
6. Join the room with 3 participants => should be ok
7. Try to join with the 4th participant with devtools > network > ws socket logs open. => gets a `disconnected` status and there's no sign of infinite `join_room` call loop in the ws messages.
- …

core: do not try to connect the room when there's a roomConnectionError

---

.changeset/eighty-crews-care.md
packages/media/src/webrtc/stats/StatsMonitor/metrics.ts

**Summary:**
This handles the case when headerBytes is missing in RTCStatsReport. Without this change, bitrate will be calculated as NaN in some browsers and our issue detectors don't work.

Handle headerbytes missing in rtcstatsreport

---

.changeset/young-windows-cheat.md
packages/browser-sdk/src/lib/embed/index.ts
packages/browser-sdk/src/stories/prebuilt-ui.stories.tsx

**Summary:**
This is a command for the embed element that allows developers to set up their own button to open the settings pane.
None
1. Create a localstack room to use in story book
2. Add a supported command for the button under sdk/packages/browser-sdk/src/stories/prebuilt-ui.stories.tsx
3. Run yarn dev and navigate to Prebuilt-UI Stories -> Embed Element Example
4. Click button, settings page should open to the defined pane
N/A
-   [x ] My code follows the project's coding standards.
-   [ x] Prefixed the PR title and commit messages with the service or package name
-   [ x] I have written unit tests (if applicable).
-   [ x] I have updated the documentation (if applicable).
-   [ x] By submitting this pull request, I confirm that my contribution is made
under the …

browser-sdk: open_settings command

---

.changeset/nine-maps-appear.md
packages/core/src/redux/slices/remoteParticipants.ts

**Summary:**
We need to keep remote clients with non-human-roles in our remote state. For instance, we need to ask them for an SDP offer in P2P or a PeerConnection wont be established.
closes #359 

Fix P2P SDP negotiation with non-human-role clients

---

apps/react-native-webview-example/app/room/index.tsx
apps/react-native-webview-example/package.json
yarn.lock

**Summary:**
Add brief example on how to explicitly handle media permissions on Android platform, from the host (demo) app. 
No changeset added since this touches the demo app only. 
Initial step: Set the `ROOM_URL` in `apps/react-native-webview-example/app/room/index.tsx`
1. Using an Android device: try to join the room using current master branch and confirm that the screen is stuck when asking for permissions. Checkout this current branch and re-run the app: now the permissions are explicitly granted and you are able to join the room normally. 
2. Confirm that the iOS app is not affected and you are still able to join a room normally. 
-   [x] Prefixed the PR title and commit messages with the service or package …

react-native-sdk: Add Android media permission example to RN demo app

---

.changeset/fuzzy-terms-prove.md
apps/react-native-webview-example/app/room/index.tsx
packages/react-native-sdk/src/embed/index.tsx

Adds event listeners for events happening in the room. There's a catch-all listener `onWherebyEvent`, that will trigger on any Whereby event, and there's specific listeners for each one, like `onReady` for example. All of them are typed, and we expose the `WherebyEvent` type as well, so that it can be used (see the react native example app for example usage).
**Summary:**
Test by running the react native example app, and see the event log.
under …

react-native-sdk: Add event listeners for Whereby events

---

.changeset/strong-nails-boil.md
apps/react-native-webview-example/app/room/index.tsx
packages/react-native-sdk/src/embed/index.tsx

Add the post commands to react native SDK. Allows for commands to be triggered on the consumer react native app. 
Added 3 buttons in the example app to make it easy to test. We can remove some of them if it's too much.
**Summary:**
1. `yarn build` and run the react native example app
2. Test the new buttons

react-native-sdk: Add post commands

---

.changeset/lemon-socks-promise.md
.changeset/two-yaks-fly.md
packages/core/src/redux/slices/rtcConnection/index.ts
packages/media/src/webrtc/types.ts

**Summary:**
* if we are an Node.JS SDK app, let RtcManager know so we can customise ICE negotiation.
* if remote participant is dial-in, enforce TURN TLS. Will be changed to TURN UDP in RtcManager if we are an Node.JS SDK app.

Enforce TURN for dial-in peer connections

---

.changeset/big-bulldogs-work.md
packages/react-native-sdk/src/embed/index.tsx

**Summary:**
Add `sdkPlatform` URL parameter to react native embed component. 
1. Run the react native demo app (after setting the room URL). Open Posthog and confirm that, for instance, the `Visited room` event for that room now contains the `sdkPlatform` URL parameter set to `react-native-embed`. 

Track usage from react native embed component

---

.changeset/hip-knives-draw.md
packages/browser-sdk/src/lib/react/useRoomConnection/index.ts
packages/browser-sdk/src/lib/react/useRoomConnection/types.ts

Fixes #404 
Fix typings for `useRoomConnection` actions. These are currently defined as "class member functions" instead of "function-valued properties". The actions object is actually a record with function-valued properties, which is the reason for this change.
The other issue mentioned in #404 is actually different to the typing issue. The infinite loop will currently happen when creating a `useEffect` like this:
```
useEffect(() => {
joinRoom();
return () => leaveRoom();
}, [joinRoom, leaveRoom]);
```
This is because of the dependencies in `whenConnectedToRoom`, which currently depends on `roomConnectionStatus`, which changes frequently and will therefore recreate the function, which in turn will trigger the useEffect. This is not correct, and we should not depend on changes to …

browser-sdk: Fix infinite loop issue with leave room fn

---

.changeset/pink-turkeys-juggle.md
packages/react-native-sdk/package.json

`react-native-webview` should be listed as a normal dependency and not a dev dependency, so that consumers installs it when installing the SDK.
**Summary:**

react-native-sdk: Move webview dependency to normal dependencies

---

.changeset/fifty-horses-swim.md
packages/core/src/redux/index.ts
packages/core/src/redux/slices/__tests__/connectionMonitor.unit.ts
packages/core/src/redux/slices/connectionMonitor.ts
packages/core/src/redux/store.ts
packages/core/src/redux/tests/store/connectionMonitor.spec.ts
packages/media/src/webrtc/stats/IssueMonitor/index.ts

Add connection monitor to send `insightsStats` custom events to the rtcstats server at regular 2 second intervals.
1. Download this branch and run: `yarn build && yarn dev`
2. When Storybook opens in a browser window, navigate to the "Custom UI > Room Connection Only" story
3. Open the developer tools and then focus the "Network" tab
4. Add a filter for wss://rtcstats.srv.whereby.com/iframe.html in the Developer tools Network tab.
5. Click "Join room" button in the story
6. Also join the room from another browser tab with a second participant.
7. In the developer tools opened in Step 3 above, you should now see `insightsStats` flowing from the story to the rtcstats server.
-   [x] Prefixed the PR title and commit messages with the …

core: Add connection monitor events insightsStats

---

.changeset/wet-trainers-run.md
packages/core/src/redux/slices/__tests__/rtcConnection.unit.ts
packages/core/src/redux/slices/rtcConnection/index.ts
packages/core/src/redux/slices/signalConnection/index.ts
packages/core/src/redux/tests/store/signalConnection.spec.ts
packages/media/src/webrtc/P2pRtcManager.ts
packages/media/src/webrtc/RtcManagerDispatcher.ts
packages/media/src/webrtc/VegaRtcManager/index.ts
packages/media/src/webrtc/rtcStatsService.ts
packages/media/src/webrtc/types.ts

Refactor of the RTCStats WebSocket connect timing so that the rtcstats service is only connected when an RTC Manager has also been created (i.e. remove connection on initialization of RTCStats WebSocket).
This fixes two bugs in the SDK:
* The rtcstats websocket connection is now only connected when a joinRoom action is invoked. Previously the rtcstats websocket connection was opened before any invocation of SDK code and would remain sitting idly open until a joinRoom action was triggered.
* The rtcstats websocket connection now re-opens correctly on a leave->re-join->... flow within the app (and on every subsequent re-join).
1. Download this branch and run: `yarn build && yarn dev`
2. When Storybook opens in a browser window, navigate to the "Custom UI > Room Connection Only" story
3. …

media: Refactor RTCStats WebSocket connect timing

---

.changeset/strange-apples-divide.md
packages/core/src/redux/slices/rtcConnection/index.ts
packages/media/src/webrtc/P2pRtcManager.ts
packages/media/src/webrtc/types.ts

**Summary:**
There were many problems with p2p node clients, so we tried a new webrtc implementation in node: https://github.com/WonderInventions/node-webrtc
After adding this, we had some problems with SFU rooms. We fixed it by using a different mediasoup device handler.
This lib also removes the need for TURN enforcement on p2p node agents
https://linear.app/whereby/issue/COB-1012/p2p-no-audio-if-there-are-more-than-1-dialed-in-users
I'll add notes for testing on the recording-service side
-   [ ] By submitting this pull …

Remove TURN enforcement, change node client mediasoup device handler

---

.changeset/khaki-peaches-taste.md
packages/media/src/webrtc/P2pRtcManager.ts
packages/media/src/webrtc/Session.ts
packages/media/src/webrtc/rtcManagerEvents.ts
packages/media/src/webrtc/sdpModifier.ts
packages/media/tests/webrtc/sdpModifier.spec.ts

This PR adds an option to clean sdp before setLocalDescription, hopefully working around browser bugs like:
https://issues.webrtc.org/issues/41480892
(and a similar one on Firefox)
It adds events so we can track these kind of errors in our apps
It removes the pendingOffer logic as that was a workaround for a bug long time ago, and interfered with the tracking/events, and makes sure the offer isn't sent to remote end before working locally.
Testing instructions in PWA PR

media: handle sdp errors

---

.changeset/fair-hairs-tease.md
packages/core/src/redux/slices/roomConnection.ts
packages/core/src/redux/tests/store/roomConnection.spec.ts

If the room is not locked/you are already connected to the room - we should not fire a knock event and change the connection status to `knocking`. This should not happen with correct usage, but we've seen at least one question around this, so better to put in this guard. If you try to knock and the room is not locked, we just send a warning in the console and do not fire the signal event.
**Summary:**
1. Download this snippet as `tmp_knock.patch`. This will just show the knock button regardless of the connection status in storybook
```diff
diff --git a/packages/browser-sdk/src/stories/components/VideoExperience.tsx b/packages/browser-sdk/src/stories/components/VideoExperience.tsx
index 6be36c98..69559d87 100644
--- …
```

core: Do not allow knocking if room is not locked

---

.changeset/metal-shirts-sparkle.md
packages/media/src/webrtc/P2pRtcManager.ts

This adds options for adding google and cloudflare stun servers for P2P calls. Testing instructions in PWA PR
(most of the changes are by prettier)

media: Option for adding google and cloudflare stun servers

---

.changeset/khaki-humans-add.md
packages/browser-sdk/src/lib/react/Grid/index.tsx
packages/browser-sdk/src/stories/video-grid-ui.stories.tsx

Currently we don't auto-mute the video view of the local participant in the videogrid, which will cause echo when using the default grid. An oversight that wasn't caught because the storybook for the video grid had `audio: false` in the local media options for the room connection, meaning we never got the echo issues there..
**Summary:**
1. Go to Video Grid story
2. Verify that there's no echo

browser-sdk: Auto mute video cell of local participant in video grid

---

.changeset/loud-donkeys-exercise.md
packages/core/package.json

We generate `legacy-esm.js` but currently don't list `.js` files in the package.json, so it's not included in the NPM package.
Fixes #483 
**Summary:**

core: Add js files in package.json

---

.changeset/mighty-seals-drum.md
packages/browser-sdk/src/lib/react/Grid/index.tsx

Show a placeholder (avatar) when there no stream for a participant in the video grid. Kind of an edge case since `isVideoEnabled` needs to be true as well, but we had a report for this from a customer. 
**Summary:**
I couldn't reproduce this just by blocking media permissions (`isVideoEnabled` would be `false`). I created a patch to verify though, and this can be used to test:
1. On main: Save this snippet as `tmp_no_stream.patch`, and apply it `git apply tmp_no_stream.patch`
```diff
diff --git a/packages/core/src/redux/slices/remoteParticipants.ts b/packages/core/src/redux/slices/remoteParticipants.ts
index 3d1d9de9..2a7a835a 100644
--- a/packages/core/src/redux/slices/remoteParticipants.ts
+++ b/packages/core/src/redux/slices/remoteParticipants.ts
@@ -25,7 +25,8 @@ …
```

browser-sdk: Show placeholder cell when there's no stream

---

.changeset/silly-students-hope.md
packages/browser-sdk/src/lib/react/Provider/hooks.ts
packages/browser-sdk/src/lib/react/Provider/index.tsx
packages/browser-sdk/src/stories/custom-ui-with-redux.stories.tsx
packages/browser-sdk/src/stories/redux-store.tsx

Currently, we don't support consumer apps using a redux store. This is because our redux context will interfere with their redux context, and you will get an error like this:
We can solve this by using a custom redux context, as done in this PR. I've added a storybook entry that has it's own small redux store, so we can test this. 
**Summary:**
1. Download this snippet as `tmp_redux_patch.patch`, and apply it with `git apply tmp_redux_patch.patch`.
```diff
diff --git a/packages/browser-sdk/src/lib/react/Provider/hooks.ts b/packages/browser-sdk/src/lib/react/Provider/hooks.ts
index ecd2d03c..0ae6be21 100644
--- a/packages/browser-sdk/src/lib/react/Provider/hooks.ts
+++ b/packages/browser-sdk/src/lib/react/Provider/hooks.ts
@@ -1,5 +1,5 @@
+import { useDispatch, …
```

browser-sdk: Add custom redux context

---

.changeset/soft-pets-think.md
packages/media/src/webrtc/P2pRtcManager.ts

**Summary:**
Not emit NO_PUBLIC_IP_GATHERED event in case the PC ICE Agent connected with host candidates.

media: If ICE connected not emit no_public_ip_gathered

---

.github/workflows/e2e.yml
apps/sample-app/test/testsuites/screenshare.spec.ts
apps/sample-app/test/testsuites/video.spec.ts

`macos-12` is deprecated, see here: https://github.com/whereby/sdk/actions/runs/12013440065/job/33486964269?pr=491
Let's try `macos-latest`.
I'm disabling (only on webkit) two tests that are failing on macos-latest. We have a ticket to look in to this later.
**Summary:**
1. e2e tests should pass

e2e: Update macos runner

---

.changeset/swift-pandas-study.md
packages/media/src/webrtc/BandwidthTester.ts

The `getMediasoupDevice` call was throwing because we don't actually pass features into the BandwidthTester from PWA
**Summary:**
1. add this canary to PWA
1. run a bandwidth test

Handle missing features in BandwidthTester

---

.changeset/cyan-elephants-shake.md
packages/media/src/utils/__tests__/getMediasoupDevice.spec.ts
packages/media/src/utils/getMediasoupDevice.ts

-------
**Summary:**
There were some browser edge cases where Safari17 handler was being returned with the flag disabled, which is bad
1. add this canary to PWA and go to an SFU room in iOS Safari and another browser
1. make sure you can hear the iOS safari client
2. 

media: Only use Safari17 handler when flag is eanbled

---

.changeset/real-cougars-live.md
packages/media/src/utils/Safari17Handler.ts

node complains about them when running recording service workers
-------
**Summary:**
1. add media canary to PWA and join an SFU room with url params `?safari17HandlerOn&stats` in chrome and safari
1. make sure the video streams are rate limited in both browsers (OUT rates should roughly match this:)
1. go to the recording-service repo, checkout `dependabot/npm_and_yarn/whereby.com/core-0.32.1` and `yarn && yarn workspace captioner-worker start` - you should see an error like:
```bash
/Users/kevinhanna/repos/whereby/recording-service/node_modules/.bin/tsc
node:internal/process/esm_loader:34
internalBinding('errors').triggerUncaughtException(
^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/kevinhanna/repos/whereby/recording-service/node_modules/mediasoup-client …
```

media: fix mediasoup imports

---

.changeset/fair-bananas-explode.md
packages/media/src/utils/ServerSocket.ts
packages/media/src/webrtc/VegaConnectionManager.ts
packages/media/src/webrtc/VegaRtcManager/index.ts
packages/media/src/webrtc/rtcManagerEvents.ts
packages/media/tests/webrtc/VegaConnectionManager.spec.ts

This adds a connection manager that allows multiple failover hosts to be tested/used. When activated by feature `sfuConnectionManagerOn`, it will replace the old `connect()` logic with a new one. If using multiple hosts they must be specified in `sfuServers` (originating from signal), or `sfuServersOverride` (from prefs), otherwise it will use a single host (but new connect()) like before.
Testing instructions in PWA PR

media: createVegaConnectionManager

---

.changeset/sour-steaks-push.md
packages/core/src/redux/slices/__tests__/app.unit.ts
packages/core/src/redux/slices/__tests__/rtcConnection.unit.ts
packages/core/src/redux/slices/app.ts
packages/core/src/redux/slices/rtcConnection/index.ts
packages/core/src/redux/tests/store/rtcConnection.spec.ts
packages/media/src/utils/types.ts

Ensure that captioner workers accepts all streams, regardless of breakout groups.
**Summary:**
Testing instuctions in the related PR here: https://github.com/whereby/recording-service/pull/729

common: Exclude captioner in breakout groups

---

.changeset/nine-rats-kiss.md
packages/media/src/utils/__tests__/mediaSettings.spec.ts
packages/media/src/utils/mediaSettings.ts
packages/media/src/webrtc/P2pRtcManager.ts

-------
**Summary:**
We were getting the preferred codecs from RTCRtpSender, but Chrome on Mac
supports sending a higher version of H264 than it can receive. See here:
https://groups.google.com/g/discuss-webrtc/c/QS7y-7zR5ok
This was causing chrome to fail to set our preferred codecs with an
error like:
InvalidModificationError: Failed to execute 'setCodecPreferences' on
'RTCRtpTransceiver': Invalid codec preferences: invalid codec with name
"H264".
So instead we get the capabilities from RTCRtpReceiver, sort
them for our preferred codecs when the relative flags areenabled
(instead of adding newcodecs), then set them on the transceiver.
This allows us to enable both AV1 and VP9 flags simultaneously, where
before an early VP9 entry would break the loop, leaving AV1 stuck near
the bottom of …

media: fix chrome setCodecPreferences

---

.changeset/nice-spiders-taste.md
packages/core/src/redux/slices/rtcConnection/index.ts

Export the internal `rtcEvents` from the core package.

core: Export `rtcEvents` from package

---

.changeset/slimy-clocks-divide.md
packages/browser-sdk/src/lib/embed/index.ts

Adds `cancel_knock` event. 
**Summary:**
Test with PWA PR: https://github.com/whereby/pwa/pull/4296
1. Save this snippet as tmp_cancel_knock.patch, and apply it `git apply tmp_cancel_knock.patch`
```diff
diff --git a/packages/browser-sdk/src/stories/prebuilt-ui.stories.tsx b/packages/browser-sdk/src/stories/prebuilt-ui.stories.tsx
index f8cd18eb..e8c61a69 100644
--- a/packages/browser-sdk/src/stories/prebuilt-ui.stories.tsx
+++ b/packages/browser-sdk/src/stories/prebuilt-ui.stories.tsx
@@ -92,6 +92,10 @@ const WherebyEmbed = ({
setMeetingEnded(true);
});
+        element?.addEventListener("cancel_knock", () => {
+            console.log("cancel_knock");
+        });
+
}, []);
return (
```
2. `yarn build && yarn dev`
3. Go to prebuilt UI story (make sure the room you are …

browser-sdk: Add cancel knock event to embed element

---

.changeset/silent-pillows-hear.md
packages/media/src/utils/mediaSettings.ts
packages/media/src/webrtc/P2pRtcManager.ts
packages/media/src/webrtc/VegaRtcManager/index.ts
packages/media/src/webrtc/sdpModifier.ts

So we can control these independently
**Summary:**
1. add the media canary to your local PWA on this branch https://github.com/whereby/pwa/pull/4324
2. join a p2p room with `?debug&stats` in two chrome clients
3. see the video streams are VP8
4. add the `p2pVp9On` flag to both URLs, see VP9 codec is used
5. add add the `p2pAv1On` flag to both URLs, see AV1 codec is used
6. remove the flags and add `sfuVp9On&sfuAv1On` and see the streams go back to VP8
7. with those two flags on, in the console run `store.selectFeatureSfuAv1On()` and `storeSelectFeatureSfuVp9On()` and see both are true
-   [ ] I have written unit tests (if …

media: Split vp9On and av1On flags to be room mode aware

---

.changeset/clever-planets-clap.md
packages/media/src/webrtc/VegaRtcManager/index.ts

I updated the calls to getMediaSettings when I added these new codec flags and accidentally changed a true to a false 🙃 
**Summary:**
1. add current media lib to local-stack PWA and run the screen-premium e2e suite, it should fail saying the stream resolution isn't correct
2. add this canary to PWA and repeat the test, it should pass
-   [x ] My code follows the project's coding standards.
-   [] I have written unit tests (if applicable).

media: fix isScreenshare flag when sending sfu screenshare

---

.changeset/poor-comics-hear.md
packages/media/src/webrtc/VegaRtcManager/index.ts

Fixes a missed vp9On flag change for modifyMediaCapabilities
**Summary:**
1. in local stack pwa, `yarn add @whereby.com/media` to get the latest (broken, oops) media version
1. join an SFU room with `?stats&sfuVp9On` in two clients and see the stream doesn't work
1. `yarn add @whereby.com/media@0.0.0-canary-20250328175521` and rejoin the room from both clients, see the stream works and is VP9
-   [x ] My code follows the project's coding standards.
-   [ x] Prefixed the PR title and commit messages with the service or package name
-   [x ] I have updated the documentation (if applicable).

media: fix vp9On for modifyMediaCapabilities

---

.changeset/honest-news-notice.md
packages/media/src/utils/mediaSettings.ts
packages/media/src/webrtc/P2pRtcManager.ts

**Summary:**
Just renames this flag to show it's only for P2P rooms
kevinhanna/cob-1630-orderfilter-codecs-by-powerefficiencyhardware-decoder
add the media canary to your local stack PWA and
1. Open local-stack in two clients https://ip-127-0-0-1.hereby.dev:4443/p2p-room?stats - see they use the VP8 codec
2. add &preferHardwareDecodingOn and see they switch to some other codec depending on your hardware

media: rename preferHardwareDecodingOn to preferP2pHardwareDecodingOn

---

.changeset/modern-lies-wash.md
packages/browser-sdk/src/lib/react/Grid/VideoMutedIndicator/index.tsx
packages/browser-sdk/src/lib/react/Grid/index.tsx
packages/browser-sdk/src/lib/react/VideoView.tsx
packages/browser-sdk/src/lib/react/hooks/useAudioElement.ts

**Summary:**
In the VideoGrid we were checking `participant.isVideoMuted`, and if so rendering the `VideoMutedIndicator` instead of a `GridVideoView`
However this meant that the `<audio/>` element was no longer rendered, so we pass some more props to VideoMutedIndicator and now the audio works :tada:
https://linear.app/whereby/issue/PAN-1753/camera-and-microphone-controls-issue-nextjs-sdk
1. in a test app with the current browser-sdk version, render the VideoGrid. Join a room from that app and a PWA app
2. mute the audio from the PWA app tab (i.e. make sure you can't hear the test app participant from the PWA app browser)
3. with video and mic enabled everywhere, make sure you can hear the PWA app user from the test app browser
4. mute the video on the PWA app, see that …

browser-sdk: Fix missing audio when remote participant disables video

---

.github/actions/notify-slack/action.yml
.github/workflows/exit-prerelease.yml
.github/workflows/prerelease.yml

Following the incident regarding tj-actions we have decided to use commit hashes rather than static versions in our GHAs.
No changes, the version is the same as the commit hash, this just prevents versions from being overridden with malicious code.

Using commit hashes rather than static versions in GHA

---

.changeset/rare-actors-admire.md
packages/media/src/utils/__tests__/mediaSettings.spec.ts
packages/media/src/utils/mediaSettings.ts
packages/media/src/webrtc/P2pRtcManager.ts

previously we would use VP9 even if it was inefficient
-------
sorts codecs by power efficiency _after_ we force VP9, so we don't force VP9 onto clients that aren't power efficient decoding it
**Summary:**
https://linear.app/whereby/issue/COB-1768/ensure-vp8-is-prioritized-if-vp9-flag-is-on-but-vp9-decoding-is-power
1. `yarn add @whereby.com/media@0.0.0-canary-20250424151513` to local PWA
2. enable `p2pVp9On` in your local unleash
3. join a P2P room with `?stats` in two browsers, see they use VP9
4. leave from one browser, paste this into the console of the other still in the room:
```
Object.assign(navigator.mediaCapabilities, {
decodingInfo: async ({ video: { contentType } }) => {
return { powerEfficient: !contentType.match(/vp9/i) };
},
});
```
5. rejoin from the …

media: prioritise power efficiency sorting

---

.changeset/nice-bottles-glow.md
packages/react-native-sdk/src/embed/index.tsx

From a Discord request: https://discord.com/channels/963444905282269234/1356345885314781304
Currently, we only accept boolean values for these attributes in the react-native-sdk, but as the web version accepts `"on" | "off"`, we should allow that in the react-native-sdk as well. This change adds this option, while also keeping the boolean values, so it's backwards compatible. 
**Summary:**
Run the react-native-webview example app. Change some of the attributes to test both on/off string and boolean values.
For example:
```js
audio={false}
video={"off"}
```
Should join the call with both audio and video off.
-   [ ] I have written …

react-native-sdk: Accept on/off string values for boolean attributes

---

README.md
apps/telehealth-tutorial-app/src/App.css
apps/telehealth-tutorial-app/src/App.tsx
apps/telehealth-tutorial-app/vite.config.ts

Fixes #632 
The telehealth example app is currently out-of-date. We've made several changes to the SDK since creating this example, most notable the changes to the join/leave logic. This PR just adds some basic screens for knocking and other connection statuses that we didn't handle.
**Summary:**
1. `yarn build` and `yarn install`.
2. Change the ROOM URL variable in `/apps/telehealth-tutorial-app/src/App.tsx` to a valid room url
3. Run `yarn dev:telehealth-app`
4. Verify that you can join the room and it looks OK.
-   [ ] By …

dev: Fix telehealth example app

---

.changeset/clever-grapes-ring.md
packages/media/src/utils/mediaSettings.ts
packages/media/src/webrtc/VegaRtcManager/index.ts

This will force 3 layer simulcast, or equivalent VP9 config, for additional screenshares being shared at the same time. When multiple participants are sharing their screen, the tiles will become smaller and with this PR we no longer care about keeping resolution at max in low bandwidth scenarios.
In PWA PR

media: Introduces other media settings for additional screenshares

---

.changeset/old-shoes-burn.md
packages/media/src/webrtc/VegaConnectionManager.ts
packages/media/tests/webrtc/VegaConnectionManager.spec.ts

When network is unstable, you could be losing and recovering network before the list of hosts to attempt was completed, making it sometimes using a less ideal host / datacenter than needed. With this change, the reaming attempts/host in the list is cancelled when it is signalled about network being possibly down. This is signalled when the signal server network connection is down - and will only affect SFU connection process in progress (not yet connected)
under the …

media: aborts further host connection attempts when network is seemingly

---

.changeset/silly-carrots-explain.md
packages/media/src/utils/__tests__/mediaSettings.spec.ts
packages/media/src/utils/__tests__/mockRouterRtpCapabilities.json
packages/media/src/utils/mediaSettings.ts
packages/media/src/webrtc/BandwidthTester.ts
packages/media/src/webrtc/VegaRtcManager/index.ts

-------
**Summary:**
This changes a bit of behaviour with certain flags activated:
- *sfuVp9On & h264On*: previously, these flags made _only_ these codecs work. It turns out Safari and Firefox can't encode VP9 SVC (instead of simulcast) properly, so now VP9 also includes an `isChrome` check. Secondly, the preferred codec is moved to the top of the list of router capabilities, where previously all other codecs were removed.
This change means we can have Chrome clients with VP9 & SVC in the same room as clients using VP8/H264 and simulcast - yay!
- *VP9 bandwidth limits*: Where previously with VP8 we were sending multiple streams at different qualities (simulcast), VP9 uses [SVC](https://w3c.github.io/webrtc-svc/), which allows us to encode all 3 quality levels in one stream. This means …

media: add flag to switch SVC encoding mode in VP9

---

.changeset/swift-pens-impress.md
packages/browser-sdk/package.json

Allow react19 to be used with browser-sdk, by updating peer dependencies to minimal version 18.2, not exact.
This currently works with yarn, but npm is more strict and throws an error when trying to install the browser-sdk in a react 19 project.
**Summary:**
1. Create a react 19 app (f.ex with vite)
2. Try to install the current published browser-sdk with npm `npm install @whereby.com/browser-sdk`
3. It should throw an error
4. Install this canary with npm `npm install @whereby.com/browser-sdk@0.0.0-canary-20250617101238`
5. It should work
-   [ ] I have updated the documentation (if …

browser-sdk: Allow react19 to be used

---

.changeset/modern-geese-teach.md
packages/core/src/redux/slices/organization.ts
packages/core/src/redux/slices/rtcAnalytics.ts
packages/core/src/redux/tests/store/rtcAnalytics.spec.ts

1. Enable hiding display names in your test org prefs
1. `yarn dev:sample-app` and go to http://localhost:5420, enter a room url for your test org
1. open brower dev tools network tab to capture websockets
1. set the room url to one from your test org
1. see the displayName rtc-stats message is redacted 
*The person approving this PR is REQUIRED to run the included test steps*
https://linear.app/whereby/issue/COB-1809/redact-dispaly-name-from-rtc-stats-payloads-in-sdk

core: hideInsightsDisplayNames

---

.github/workflows/build-test-release.yml
package.json

The previous merge workflow failed with this error:
```
changeset version \&\& pnpm install --lockfile-only
🦋  error Too many arguments passed to changesets - we only accept the command name as an argument
Existing pull requests: []
```
It's adding `\` for some reason to the command. It should look like this: `pnpm changeset version && pnpm install --lockfile-only`.
Moving this to the package json should fix it. 
**Summary:**
under the terms of the …

common: Fix changeset command

---

.changeset/tame-items-say.md
packages/media/src/utils/__tests__/mediaSettings.spec.ts
packages/media/src/utils/mediaSettings.ts

it uses ~15% more bandwidth and didn't show measurable improvements when tested
**Summary:**
[COB-1921: remove svcKeyScalabilityModeOn flag](https://linear.app/whereby/issue/COB-1921/remove-svckeyscalabilitymodeon-flag)
1. add canary to your PWA
2. join an SFU room with two chromium clients with `?sfuVp9On&stats`
3. see the stream uses VP9 @ 720p, it should max out around 1mbps
4. resize the screen until the video tiles are about 2 inches wide, see it drops down to 640x360
5. resize again so they are really small, see the resolution falls again to 320X180
-   [ ] I have updated the …

media: remove option for *_KEY SVC encoding

---

.changeset/sour-buses-dance.md
packages/core/src/redux/slices/rtcConnection/index.ts
packages/media/src/utils/__tests__/mediaSettings.spec.ts
packages/media/src/utils/mediaSettings.ts
packages/media/src/webrtc/P2pRtcManager.ts
packages/media/src/webrtc/sdpModifier.ts

**Summary:**
this is default now
https://linear.app/whereby/issue/COB-1679/remove-flags-and-make-vp9-default-for-p2p
1. add canary media to your local PWA - `yarn add @whereby.com/media@0.0.0-canary-20250711131634`
2. disable p2pVp9On in local unleash
3. join a P2P room from two clients in various browsers with `?stats`
4. ensure the video codec is VP9
5. do the same from an embedded client

common: remove p2pVp9On flag

---

.changeset/wide-breads-slide.md
packages/core/src/redux/index.ts

**Summary:**
if we try to use createStore from /redux and createServices form /core there is a type mismatch because they both declare everything twice

core: export createServices from /redux
